# Generated by Django 5.1.2 on 2024-10-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0002_corporates_customuser_state_delete_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporates',
            old_name='corporate_name',
            new_name='alias',
        ),
        migrations.RemoveField(
            model_name='state',
            name='status',
        ),
        migrations.AddField(
            model_name='corporates',
            name='name',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
