# Generated by Django 5.1.2 on 2024-10-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0003_rename_corporate_name_corporates_alias_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Corporates',
            new_name='Corporate',
        ),
    ]
