# Generated by Django 5.1.2 on 2024-10-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0005_state_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='status',
        ),
    ]
