# Generated by Django 5.1.2 on 2024-10-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0006_remove_state_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporate',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='state',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
