# Generated by Django 5.1.2 on 2024-10-25 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0007_alter_corporate_description_alter_state_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='OtherUser',
        ),
    ]
