# Generated by Django 5.1.2 on 2024-10-25 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0008_rename_customuser_otheruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otheruser',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanage.state'),
        ),
    ]
