# Generated by Django 5.1.2 on 2024-10-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0009_alter_otheruser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'disabled'), ('pending approval', 'Pending Approval'), ('inactive', 'Inactive')], default=True, max_length=200),
        ),
    ]
