# Generated by Django 5.1.2 on 2024-10-28 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0010_state_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='otheruser',
            name='corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanage.corporate'),
        ),
    ]
