# Generated by Django 5.1.2 on 2024-10-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0011_otheruser_corporate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='status',
        ),
    ]
