# Generated by Django 5.1.2 on 2024-10-28 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0012_remove_state_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporate',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanage.state'),
        ),
    ]
